### ISSUE TITLE
MVS Compiler VERSION OF 2019.07

### ISSUE THREAD

**Issue by MarcoVerpelli** [StanfordPascal/Pascal#1]
Hello,
I think I found a minor bug in the last version

    ** Warning P221: PROCEDURE/FUNCTION "PARSEEL" NOT USED

                       ....5...10....5...20....5...30....5...40....5...50....5...60....5...70..

   ****       1 Warning.
   ****    1041 LINE(S) READ,   58 PROCEDURE(S) COMPILED,
   ****    2474 P_INSTRUCTIONS GENERATED,   0.34 SECONDS IN COMPILATION.

   **** Last Error/Warning on Line 1041

   **** Error/Warning Codes for this Program:

   **** P221: PROCEDURE/FUNCTION "%" NOT USED
   **** STANFORD PASCAL POST-PROCESSOR, OPPOLZER VERSION OF 2019.07

shouldn't "%" be the name of the procedure?

Thank you

Marco

**Comment by StanfordPascal** [comment]
Hello Marco, 
thank you for your interest in New Stanford Pascal. 
This is no error; when the compiler lists the errors occured at the end of the program, 
it lists every error type only once. P221 is an error with parameters (in this case the procedure name); 
in the error repository (file PASCAL.MESSAGES), the parameter position is marked by a percent sign. 
The error list at the end reports every error type only once without replacing the percent sign with the actual value; this is only done at the real error position (see your example, the percent sign is replaced by PARSEEL). 
Maybe the summary of all error types occured at the end is not helpful at all, and it could be omitted? 
At least from the console output? 
Please share your opinions. 
Kind regards
Bernd

**Comment by MarcoVerpelli** [comment]
Hi Bernd,
Maybe it's just me not understanding the meaning of that "%".
Since you ask me for an opinion, I think it is better to eliminate the summary of errors.

Thanks for the time you spend on the maintenance of the compiler
Marco
