### ISSUE TITLE
Suggestions for optional changes

### ISSUE THREAD

**Issue by electric-socket** [StanfordPascal/Pascal#2]
Hi, my name is Paul. I have a suggestion. Or maybe more than one.

I have been thinking about this for several months (actually, probably more than a year). I, too, have been working on a small self-hosing pascal compiler called XDPascal. It, unfortunately, only generates code for IA32/AMD32 processors running on Windows. But it is self-hosting, and can generate programs that can do some actual work and solve some problems, if a text-only interface is acceptable.

In my opinion, "small" Pascal compilers like XDPascal (about 15,000 lines) or New Stanford Pascal Compiler, Oppolzer Version "NSPCOV" (44,452 lines) are more of a teaching tool than a serious, World-Class system capable of creating current applications. I mean, seriously, if someone wants a "full-service, World Class Pascal Compiler" they'd almost certainly use Free Pascal (about 250,000 lines of code, plus tens of thousands of lines  of run-time libraries), since it targets about a dozen different architectures and operating systems. Given that to be the case, if a compiler such as mine or yours is used, it is almost certainly done for pedagogical use, for learning about how compilers work, and how someone can add a feature (or bug fix) and see what happens. 

Programs like XDPascal and NSCPOV provide an accessible platform - something where a single person can have either an understanding of the whole application, or at least understand the part they want to change -    for learning about the internals of a compiler, and maybe have some fun with it. (I'm presuming you enjoyed the challenge of adding features to and squashing bugs in NSPCOV; I know I had a lot of fun working on XDPascal.)

So now there are some suggestions I'd like to offer for the New Stanford Pascal Compiler, Oppolzer Version. I'll put them in order of (what I think is) importance.
* Consider, instead of generating specialized P-Code for a fictional machine no one uses, as a means to generate machine independent code, to generating LLVM Intermediate Representation code. LLVM has become the standard in compiler architecture. Both Free Pascal and Free Basic compilers offer optional LLVM IR code output. For a lot of people, understanding LLVM IR is relatively difficult. This might be a way to also make that accessible to more people. If you learn more about this, it might even give you ideas, and you might learn something, even if you decide not to go this route. Note that LLVM does have a translator from IR to 370 object modules, in addition to more popular targets like x86 or x64. <br/><br/>
I once considered doing a port of Free Pascal to the 370 architecture. The system is very modular, so that different architectures and operating systems, but it is so complex I figure it would take probably two years full-time work to come up to speed on it and then be able to figure out how to add S/379 code generation, plus developing run-time libraries for various mainframe operating systems. On the other hand, I was able to make my first update to XDPascal within two weeks of looking at the source code.<br/><br/> 
Actually, until I found XDPascal and the smaller size (with only slightly different features), I was going to look at making Stanford Pascal more useful as a pedagogical tool, perhaps by creating an alternative code generator that creates code other than P-code, or provide more information about how code is generated., such as flags that can be turned on or off to show the various procedures and functions used in compiling a piece of code.
* Continue accepting (* *), { } and /* */ for block comments, but don't use /* */ in the compiler. That makes it possible to compile the compiler on other compilers that don't support C-style block comments. Makes porting it potently easier.
* I'm not sure how many statistics are generated by NSCPOV, beyond number of lines, and compilation time. XDPascal reports compile time (usually in seconds or fractions of a second), lines compiled per second, number of procedures, functions and units compiled. It also separates procedures and functions in units vs. those in the main program, and number of variables used. At least, that's what I thought of collecting.
* Potentially add a different parser to also handle the current standard method of Pascal Compilers like XDPascal, Free Pascal, and Delphi, where the PROGRAM statement is optional, MODULE is UNIT, and a program or module USES other modules. This may be unrealistic, but I figure I should be inclusive.

In any event, thank you for reading this, and whether or not you consider any of my suggestions, i wish you continued success in whatever work you do on your compiler.

Sincerely,
Paul Robinson

**Comment by StanfordPascal** [comment]
Hello Paul, 
thank you for your message and your suggestions. I will try to answer briefly; see below. 

> 
> 
> Hi, my name is Paul. I have a suggestion. Or maybe more than one.
> 
> I have been thinking about this for several months (actually, probably more than a year). I, too, have been working on a small self-hosing pascal compiler called XDPascal. It, unfortunately, only generates code for IA32/AMD32 processors running on Windows. But it is self-hosting, and can generate programs that can do some actual work and solve some problems, if a text-only interface is acceptable.
> 
> In my opinion, "small" Pascal compilers like XDPascal (about 15,000 lines) or New Stanford Pascal Compiler, Oppolzer Version "NSPCOV" (44,452 lines) are more of a teaching tool than a serious, World-Class system capable of creating current applications. I mean, seriously, if someone wants a "full-service, World Class Pascal Compiler" they'd almost certainly use Free Pascal (about 250,000 lines of code, plus tens of thousands of lines of run-time libraries), since it targets about a dozen different architectures and operating systems. Given that to be the case, if a compiler such as mine or yours is used, it is almost certainly done for pedagogical use, for learning about how compilers work, and how someone can add a feature (or bug fix) and see what happens.
> 

In fact, I am using my compiler to do some significant work for my customer; 
but indeed not for continuing production work, but instead for one-time analytical 
programs, which are fast to write and easy to test. 

> Programs like XDPascal and NSCPOV provide an accessible platform - something where a single person can have either an understanding of the whole application, or at least understand the part they want to change - for learning about the internals of a compiler, and maybe have some fun with it. (I'm presuming you enjoyed the challenge of adding features to and squashing bugs in NSPCOV; I know I had a lot of fun working on XDPascal.)
> 

Me too with Stanford Pascal :-) 
I'm doing this since 2011 and in a significant manner since 2016, 
when I managed to port the mainframe-only Stanford compiler to Windows etc. 

> So now there are some suggestions I'd like to offer for the New Stanford Pascal Compiler, Oppolzer Version. I'll put them in order of (what I think is) importance.
> 
>     * Consider, instead of generating specialized P-Code for a fictional machine no one uses, as a means to generate machine independent code, to generating LLVM Intermediate Representation code. LLVM has become the standard in compiler architecture. Both Free Pascal and Free Basic compilers offer optional LLVM IR code output. For a lot of people, understanding LLVM IR is relatively difficult. This might be a way to also make that accessible to more people. If you learn more about this, it might even give you ideas, and you might learn something, even if you decide not to go this route. Note that LLVM does have a translator from IR to 370 object modules, in addition to more popular targets like x86 or x64. 
>       I once considered doing a port of Free Pascal to the 370 architecture. The system is very modular, so that different architectures and operating systems, but it is so complex I figure it would take probably two years full-time work to come up to speed on it and then be able to figure out how to add S/379 code generation, plus developing run-time libraries for various mainframe operating systems. On the other hand, I was able to make my first update to XDPascal within two weeks of looking at the source code.
>       Actually, until I found XDPascal and the smaller size (with only slightly different features), I was going to look at making Stanford Pascal more useful as a pedagogical tool, perhaps by creating an alternative code generator that creates code other than P-code, or provide more information about how code is generated., such as flags that can be turned on or off to show the various procedures and functions used in compiling a piece of code.
> 

I looked at LLVM, but I had indeed the problem that there was no easy way (for me) 
to understand the LLVM IR language and how I could get started generating such code 
from my Pascal variant. In constrast, I did significant extensions and corrections to 
the P-Code language  which is completely different now from the 1982 P-Code language, 
and I am trying to write a new "stage 2" translator, which maybe understands 
a slightly different P-Code. To me, P-Code is much more readable than LLVM. 

Some history: UCSD Pascal did the same (extending the classical P-Code to 
something called U-Code) and, as I found out recently, IBMs Pascal/VS was 
created by first defining another internal representation based on P-Code 
and then using Stanford Pascal as bootstrap to compile the new 
Pascal/VS compiler (which is self-hosted, too). So in some sence, 
Pascal/VS is an offspring of Stanford Pascal, too, with a different flavor 
of P-Code. 

BTW: I also thought about adding S/370 support to FreePascal first, but soon 
realized that there was a strong relation to ASCII code in the FreePascal source 
scanners etc., and there was no interest in the FreePascal community for such 
support. Some time after that experience, I discovered Stanford Pascal and 
took my own route :-) 

>     * Continue accepting (* _), { } and /_ _/ for block comments, but don't use /_ */ in the compiler. That makes it possible to compile the compiler on other compilers that don't support C-style block comments. Makes porting it potently easier.
> 

This is a very interesting suggestion which is easy to to, 
and I will try to do this in the near future. 

>     * I'm not sure how many statistics are generated by NSCPOV, beyond number of lines, and compilation time. XDPascal reports compile time (usually in seconds or fractions of a second), lines compiled per second, number of procedures, functions and units compiled. It also separates procedures and functions in units vs. those in the main program, and number of variables used. At least, that's what I thought of collecting.
> 

The compiler has all sort of information at hand, 
and it would be easy to provide such information. 
For me, a big plus was when I added the warnings for unused variables, 
procedures etc. 

>     * Potentially add a different parser to also handle the current standard method of Pascal Compilers like XDPascal, Free Pascal, and Delphi, where the PROGRAM statement is optional, MODULE is UNIT, and a program or module USES other modules. This may be unrealistic, but I figure I should be inclusive.
> 

Interesting. I must admit that I don't know much about the syntax of other 
Pascal variants; my first priority in this area is to add %INCLUDE statements
(a simple macro processor); this is the IBM Pascal/VS heritage. 
Include members should contain EXTERNAL definitions, like in C. 
But maybe I should look first what USES does. 

> 
> In any event, thank you for reading this, and whether or not you consider any of my suggestions, i wish you continued success in whatever work you do on your compiler.

Thank you very much. Same to you and your efforts. 

> 
> Sincerely, Paul Robinson

Kind regards

Bernd Oppolzer

**Comment by electric-socket** [comment]
The variant of Pascal that Free Pascal and my XDPascal works like this:

A main program has either no program statement OR
PROGRAM somename; (* files no longer need to be declared in the header *)

A separate compilation unit starts with

UNIT somenamedunit;

In either the main program or a unit, if this module needs to reference another unit, it has:

USES unit1, unit2, ... unitN;

Then in a unit you have

INTERFACE

Here the unit declares all constants, types, variables, procedures and functions that it exposes and makes accessible to the main program or other unit. You only give the header of the procedure or function, it has an implicit FORWARD; statement after the declaration.

Next comes 
IMPLEMENTATION
All  constants, types, variables that are private to this unit, the body of all public functions and procedures declared in INTERFACE, as well as the complete contents of any private procedure or function.  

Building programs as units allows some constants, types, variables to be hidden from other units. Related ones can be in a specific unit.  You've probably gotten to the limit on how much to put in one module. I think it can make a program easier to understand.

Also, every main program  has an implicit 
USES system;
This is where_system files, default variables and any run-time setup would occur. This unit is visible to all units.

So that is the basic overview of unit references.

Thanks for reading
Paul

**Comment by StanfordPascal** [comment]
Hello Paul, 

many thanks for your comment; it's much like a tutorial for me. 
I would like to ask some questions, if you don't mind ... see below. 
Maybe it is not too difficult to implement this with New Stanford Pascal. 

> 
> 
> The variant of Pascal that Free Pascal and my XDPascal works like this:
> 
> A main program has either no program statement OR PROGRAM somename; (* files no longer need to be declared in the header *)
> 

AFAIK, external files work with NSP without being mentioned in the program header, too. 

> A separate compilation unit starts with
> 
> UNIT somenamedunit;
> 
> In either the main program or a unit, if this module needs to reference another unit, it has:
> 
> USES unit1, unit2, ... unitN;
> 
> Then in a unit you have
> 
> INTERFACE
> 

there is no semicolon after INTERFACE, right? 

> Here the unit declares all constants, types, variables, procedures and functions that it exposes and makes accessible to the main program or other unit. You only give the header of the procedure or function, it has an implicit FORWARD; statement after the declaration.
> 
> Next comes IMPLEMENTATION All constants, types, variables that are private to this unit, the body of all public functions and procedures declared in INTERFACE, as well as the complete contents of any private procedure or function.

and again: no semicolon after IMPLEMENTATION ??

> 
> Building programs as units allows some constants, types, variables to be hidden from other units. Related ones can be in a specific unit. You've probably gotten to the limit on how much to put in one module. I think it can make a program easier to understand.
> 
> Also, every main program has an implicit USES system; This is where_system files, default variables and any run-time setup would occur. This unit is visible to all units.
> 
> So that is the basic overview of unit references.
> 
> Thanks for reading Paul

IMO, a program which contains a USES clause could be compiled by doing this: 

reading the source of the unit which is mentioned in the USES clause, 
then copying all the types and constants etc., which are mentioned in the 
INTERFACE there. And the procs and functions, too, but with EXTERNAL appended. 

Not sure about variables, though. At the moment, I don't support external (global) variables, 
only procedures and functions. Types are no problem, because they are simply declarations. 
Maybe there is a problem with structured constants; maybe they are physcially stored twice, 
if contained in such an INTERFACE; this is ugly, but not really a problem. 

External names are limited to 8 chars with NSP, due to the mainframe heritage. 

But anyway: even with these limitations, I could imagine that this extension would be good. 
In fact, copying the declaration from the modules and appending the EXTERNAL attribute
(that's what I do now) is very annoying. The USES ... INTERFACE mechanism looks much 
nicer and is an approximation to the "Standard". 

I will think about it. Please drop me some comments, if you like. 

Thank you very much, kind regards 

Bernd

**Comment by electric-socket** [comment]
In the latest incarnation of Pascal, (Extended Pascal or Object Pascal) they make a few minor (or perhaps not so minor) changes:

You are correct that IMPLEMENTATION and INTERFACE are special, in that they are not followed by ; just like the one exception to the rule that every statement ends with ; . The one exception is a statement or block SHALL NOT be followed by ; if it is the final statement (either a single statement or a block of BEGIN..END or REPEAT..UNTIL) if it immediately precedes an ELSE clause in IF-ELSE statement. Everywhere else - with two more exceptions - all other statements must be followed by ; (the exceptions being (1) the last statement in a block where it is optional; (2) After the last END of a unit or the main program where it is required to be followed by '.').

So the rule is, "Every statement must be followed by the semicolon (';'), except where it is optional or prohibited." Which  makes the statement completely meaningless!

The USE/USES feature as well as IMPLEMENTATION/INTERFACE, (along with some minor relaxation of certain strict rules of the standard) were added to fix issues that were complained about by Brian W. Kernighan in "Why Pascal is Not My Favorite Programming Language
http://www.cs.virginia.edu/~evans/cs655/readings/bwk-on-pascal.html (if you have not read it)

2.3.  Related program components must be kept separate
The fixed requirement of LABEL / TYPE / CONST / VAR in that order has been eliminated. These may occur in any order, provided you do not forward reference an identifier.

2.4.  There is no separate compilation
This is partially solved. In my case, for XDPascal each unit is a separate file but because the compiler creates an executable program without a load module, it has to compile everything at the same time. Object Pascal compilers get around this problem by creating "unit files" which are binary representation of the source code, with the extension .DPU for Delphi and .FPU for free pascal. What they are is basically copies of the symbol table and some information about the executable routines, so a future compiler run can figure out where identifiers are to be stored, relative to the beginning of the unit. This also solves the problem of procedural types (procedure and function) with names longer than 8 characters.

3.  Control Flow
"There is no 'break;' statement" 
There is now. It's scanned as a fake procedure call to the imaginary break procedure. It's implemented as a forward jump to the end of the construct used (FOR / REPEAT / UNTIL/ or CASE selector).

"The 'case' statement is better designed than in C, except that there is no 'default' clause"
There is now. Either ELSE or OTHERWISE can be used where a value is outside the range of all case selectors. As one nice feature, this particular clause is an automatic block statement, terminated  by the CASE's END statement, based on the expectation that an alternative for all selectors will usually have more than one statement, eliminating having to insert a BEGIN/END.

5.  Cosmetic Issues
"A function name by itself is a call of that function; there is no way to distinguish such a function call from a simple variable except by knowing the names of the functions."
Partially solved, at least with respect to how a function returns a value. Every function has a special predefined variable "result" which is the exact same type as the function. Assigning a value to the function name or assigning a value to the variable result are interchangeable.

"There is no null string,"
There is now. The compiler recognizes a:=''; where a is a string variable, to null that string.

Summary points he made
"1. Since the size of an array is part of its type, it is not possible to write general-purpose routines, that is, to deal with arrays of different sizes.  In particular, string handling is very difficult. "
The old Turbo Pascal, and XDPascal provide variable size strings defaulting to 255 byte fixed size but can be declared to be shorter. Turbo uses size counting (the 0tth byte of the string contains the current size). XDPascal uses C-Strings (0 terminated) and both provide built-in string concatenation. Object pascal supports variant strings of literally unlimited string sizes, up to the memory limit. I wrote a Free Pascal program to construct two 1 megabyte strings, concatenating smaller strings, then concatenating them into one 2 megabyte string. It worked. I suspect they do something similar to what you do, by putting a prefix code in front of a string with current and maximum size. Object Pascal supports variable-size arrays.

"4. The lack of separate compilation impedes the development of large programs and makes the use of libraries impossible"
Object Pascal solves that through UNIT/USES plus implementation of unit binary files.

The other problem being the terminal/file dichotomy, in which WRITE/WRITELN to OUTPUT comes after the first READ. There are two things that solved this: (1) I/O is done in the order specified, input is not automatically done when the program starts; (2) Windows uses the same DLL call for writing to a text file as writing to a terminal.

Oh, on a secondary matter, do you know 360/370/Z assembly language? I remember the days of using a green card to look up an instruction, then the gold card, to do programs for assembler class. Interesting times. Then the PC revolution made a lot of mainframe knowledge obsolete. And the stuff that wasn't obsolete, programmers had to learn all over again because many things that were good habits then, would have served us later.

Well, I've probably rambled on way too long, so I'll say "so long" for now.

Paul
